apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: freelance
  annotations:
    cloud.google.com/load-balancer-ip: "136.116.238.53"  # IP statique réservée dans GCP
spec:
  selector:
    app: frontend
  ports:
    - port: 80        # port f
      targetPort: 80  # port sur lequel Nginx écoute dans le Pod
  type: LoadBalancer
