apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-json
  namespace: freelance
data:
  config.json: |
    {
      "API_URL": "http://136.116.238.53:80",          
      "WEBSOCKET_API_URL": "ws://136.116.238.53:80",
      "MEDIA_URL": "https://storage.googleapis.com/freelance-media/media"
    }
