apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:

      # 1️⃣ Fixe les permissions sur le volume AVANT de démarrer Grafana
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /var/lib/grafana"]
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana

      # 2️⃣ Autorise Grafana à écrire dans le volume
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472

      containers:
        - name: grafana
          image: grafana/grafana:latest
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "200m"

          ports:
            - containerPort: 3000

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"

          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana

      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
